.\" troff_mono - troff macros for monospace formatted documents
.\" Copyright (C) 2022 FearlessDoggo21
.\" see LICENCE file for licensing information
.TH troff_mono 7 "January 31, 2022"
.SH NAME
troff_mono \- "mono" macro package for formatting documents with troff
.SH SYNOPSIS
.SY troff -mono
.IR file " ..."
.YS
.SH DESCRIPTION
The
.I mono
package of macro definitions for the
.I roff
language provides a simple output format for miscellaneous documents.
.PP
Pagination is applied automatically with the use of this macro package, however
the macros are still listed for the sake of completeness.  Alongside the traps
set, the font is changed to be monospaced, the margins are set to 1 inch, and
paragraph indentation is set to 0.5 inches.
.TS
;
l lx .
\fB.hd\fR	T{
start page by applying spacing
trapped at beginning of each page
T}
\fB.fo\fR	T{
end page by applying pagination and spacing
trapped at bottom margin of each page
T}
\fB.pg\fR	T{
begin paragraph
T}
.TE
.SH FILES
TMAC_FOLDER/ono.tmac
.SH SEE ALSO
.BR troff "(1), " troff_mla (7)
.SH AUTHOR
FearlessDoggo21
