.\" troff_mla - troff macros for mla formatted documents
.\" Copyright (C) 2022 FearlessDoggo21
.\" see LICENCE file for licensing information
.TH troff_mla 7 "January 31, 2022"
.SH NAME
troff_mla \- "mla" macro package for formatting documents with troff
.SH SYNOPSIS
.SY "troff -mla"
.IR file " ..."
.YS
.SH DESCRIPTION
The
.I mla
package of macro definitions for the
.I roff
language provides a convenient facility for preparing MLA formatted
documents.  The MLA specification defines page margins of exactly 1 inch,
paragraph indents and hanging indents (for citations) of exactly 0.5 inches,
centred titles and specific page headers, and named pagination.
.PP
Pagination is applied automatically with the use of this macro package, however
the macros are still listed for the sake of completeness.  Alongside the traps
set, the font size and vertical spacing are set to 12 point and double
respectively, and output justification and hyphenation are both disabled.
.TS
;
l lx .
\fB.hd\fP	T{
start page by applying pagination and spacing;
trapped at beginning of each page
T}
\fB.fo\fP	T{
end page by applying spacing;
trapped at bottom margin of each page
T}
\fB.pg\fP	T{
begin paragraph
T}
\fB.tt\fP	T{
begin centered title
T}
\fB.ci\fP	T{
begin hanging indent region
used for citations or headers
T}
.TE
.SH FILES
TMAC_FOLDER/la
.SH SEE ALSO
.BR troff "(1), " troff_mono "(7), " troff_hw (7)
.SH AUTHOR
Written by FearlessDoggo21
