.\" troff_hw - troff macros for generating homework documents
.\" Copyright (C) 2022 FearlessDoggo21
.\" see LICENCE file for licensing information
.TH troff_hw 7 "February 9, 2022"
.SH NAME
troff_hw \- "hw" macro package for formatting documents with troff
.SH SYNOPSIS
.SY "troff -mhw"
.IR file " ..."
.YS
.SH DESCRIPTION
The
.I hw
package of macro definitions for the
.I roff
language provides a convenient facility for generating school notes documents.
.PP
Traps are set to automatically produce margins at the top and bottom of the
page; the macros which perform this action are listed for the sake of
completion.
.TS
;
l lx .
\fB.hd\fP	T{
start page by applying spacing;
trapped at beginning of each page
T}
\fB.fo\fP	T{
end page by applying spacing;
trapped at bottom margin of each page
T}
\fB.ht\fP	T{
begin header
T}
\fB.mt\fP	T{
begin section header
T}
\fB.st\fP	T{
begin note with mdash
T}
.TE
.SH FILES
TMACPREFIX/hw
.SH SEE ALSO
.BR troff "(1), " troff_mla "(7), " troff_mono (7)
.SH AUTHOR
Written by FearlessDoggo21.
